<?php
/**
 * ReceivedInvoicesResultInvoicesInnerVatRecapitulationInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\Helios\Invoices
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iNuvio Server Invoices API
 *
 * ## Úvod    **REST API** je rozšířený standard programového rozhranní pro integraci aplikací.
 *
 * The version of the OpenAPI document: 1.2.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BeLenka\Helios\Invoices\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReceivedInvoicesResultInvoicesInnerVatRecapitulationInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ReceivedInvoicesResultInvoicesInnerVatRecapitulationInner
 * @package     BeLenka\Helios\Invoices
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReceivedInvoicesResultInvoicesInnerVatRecapitulationInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReceivedInvoicesResultInvoicesInnerVatRecapitulationInner"
     */
    public function testReceivedInvoicesResultInvoicesInnerVatRecapitulationInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat_rate"
     */
    public function testPropertyVatRate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency_amount"
     */
    public function testPropertyCurrencyAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency_amount_tax_inclusive"
     */
    public function testPropertyCurrencyAmountTaxInclusive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat_amount"
     */
    public function testPropertyVatAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
