<?php
/**
 * FakturyPijatApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\Helios\Invoices
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iNuvio Server Invoices API
 *
 * ## Úvod    **REST API** je rozšířený standard programového rozhranní pro integraci aplikací.
 *
 * The version of the OpenAPI document: 1.2.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\Helios\Invoices\Test\Api;

use \BeLenka\Helios\Invoices\Configuration;
use \BeLenka\Helios\Invoices\ApiException;
use \BeLenka\Helios\Invoices\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FakturyPijatApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\Helios\Invoices
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FakturyPijatApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for invoicesReceivedDbNameGet
     *
     * Seznam faktur přijatých.
     *
     */
    public function testInvoicesReceivedDbNameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesReceivedDbNameInvoiceIdDelete
     *
     * Smazání faktury přijaté.
     *
     */
    public function testInvoicesReceivedDbNameInvoiceIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesReceivedDbNameInvoiceIdGet
     *
     * Faktura přijatá dle ID.
     *
     */
    public function testInvoicesReceivedDbNameInvoiceIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesReceivedDbNameInvoiceIdItemsGet
     *
     * Seznam položek faktury přijaté.
     *
     */
    public function testInvoicesReceivedDbNameInvoiceIdItemsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesReceivedDbNamePost
     *
     * Vytvoření nové faktury přijaté.
     *
     */
    public function testInvoicesReceivedDbNamePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
