<?php
/**
 * FakturyVydanApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\Helios\Invoices
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iNuvio Server Invoices API
 *
 * ## Úvod    **REST API** je rozšířený standard programového rozhranní pro integraci aplikací.
 *
 * The version of the OpenAPI document: 1.2.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\Helios\Invoices\Test\Api;

use \BeLenka\Helios\Invoices\Configuration;
use \BeLenka\Helios\Invoices\ApiException;
use \BeLenka\Helios\Invoices\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FakturyVydanApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\Helios\Invoices
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FakturyVydanApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for invoicesIssuedDbNameGet
     *
     * Seznam faktur vydaných.
     *
     */
    public function testInvoicesIssuedDbNameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesIssuedDbNameInvoiceIdDelete
     *
     * Smazání faktury vydané.
     *
     */
    public function testInvoicesIssuedDbNameInvoiceIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesIssuedDbNameInvoiceIdGet
     *
     * Faktura vydaná dle ID.
     *
     */
    public function testInvoicesIssuedDbNameInvoiceIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesIssuedDbNameInvoiceIdItemsGet
     *
     * Seznam položek faktury vydané.
     *
     */
    public function testInvoicesIssuedDbNameInvoiceIdItemsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesIssuedDbNamePost
     *
     * Vytvoření nové faktury vydané.
     *
     */
    public function testInvoicesIssuedDbNamePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
